FROM python:3.10-slim

# Checkout and install dagster libraries needed to run the gRPC server
# exposing your repository to dagster-webserver and dagster-daemon, and to load the DagsterInstance

RUN pip install \
    dagster \
    dagster-postgres \
    dagster-docker

# Add repository code

RUN pip install --upgrade pip

# Создаем необходимые директории
RUN mkdir -p /opt/dagster/dagster_home /opt/dagster/app

# Копируем файлы конфигурации и код в контейнер
COPY dagster.yaml /opt/dagster/dagster_home/
COPY workspace.yaml /opt/dagster/app/
COPY dagster_npl /opt/dagster/app/dagster_npl
COPY requirements.txt /opt/dagster/app/
COPY .env /opt/dagster/app/
COPY dagster.yaml /opt/dagster/app/


# Устанавливаем зависимости
RUN pip install -r /opt/dagster/app/requirements.txt

WORKDIR /opt/dagster/app

# Run dagster gRPC server on port 4000

EXPOSE 4000

# CMD allows this to be overridden from run launchers or executors that want
# to run other commands against your repository
CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000", "-f", "definitions.py"]